### PR TITLE
Add Kavan Pancholi's details in readme

### PR DESCRIPTION
**Pull request by kavanpancholi**
Added Kavan Pancholi's details in readme

### CODE REVIEW

**Comment by pratikbutani** [comment]
@kavanpancholi  please add it in alphabetical order.

**Comment by pratikbutani** [comment]
> @kavanpancholi please add it in alphabetical order.

Also edit with new [format](https://github.com/pratikbutani/Men-GitHubers/blob/master/Contributing.md#format)

**Comment by ravirupareliya** [comment]
@kavanpancholi There is also merge conflicts if you can look into it. Sorry for inconvenience but we have changed the format of repo so if you can do the needful.

**Comment by kavanpancholi** [comment]
@ravirupareliya @pratikbutani I've updated the PR with a new format and ordered alphabetically.
LGTM now.

**Pull request merged**
